### ISSUE TITLE
Key expired at SuSE build server

### ISSUE THREAD

**Issue by sysms** [kozec/sc-controller#630]
Dear maintainer,

I just want to inform you, that the Release.key at  https://download.opensuse.org/repositories/home:kozec/Debian_10/Release.key has expired, and thus updating or installing from this repository is currently not possible.

/etc/apt/trusted.gpg.d/home_kozec.gpg
-------------------------------------
pub   rsa2048 2014-09-18 [SC] [expired: 2021-04-19]
      115F 18DC A4E1 8F67 E31A  DEA2 3B57 AE37 123C 1C64
uid           [ expired] home:kozec OBS Project <home:kozec@build.opensuse.org>

Please fix this. Thank you.

**Comment by DeniedExistence** [comment]
I'm also having this issue and cannot install via repository on deb10

**Comment by kozec** [comment]
Issue should be fixed now.

**Comment by fkleon** [comment]
Hi, this still seems to be an issue, the key has apparently not been updated.

```
pub   rsa2048 2014-09-18 [SC] [expired: 2021-04-19]
      115F18DCA4E18F67E31ADEA23B57AE37123C1C64
uid           home:kozec OBS Project <home:kozec@build.opensuse.org>
```

**Comment by sysms** [comment]
I can confirm: the key file has the same (old) date (28-Mar-2021) and has not been changed (yet).

**Comment by sysms** [comment]
They key has still not changed. 

Is there another working Debian 10 repository?

**Comment by sysms** [comment]
Thank you for finally fixing it/renewing the key!

**Comment by kozec** [comment]
> Thank you for finally fixing it/renewing the key!

Sorry for not responding. I've been trying everything, grew fed up with it and basically gave up for the day. I'm not really sure what helped but I'm glad it did in the end.
